#!/bin/bash

set -ex

docker-build() {
    if [ $# -eq 0 ] ; then
        echo "docker-build must have at least one argument." >&2
        exit 1
    fi

    local build
    build=$1
    shift

    docker build $@ $build -t jp-ellis/${build}:build
    docker save jp-ellis/$build | \
        sudo docker-squash -verbose -t jp-ellis/${build}:latest | \
        docker load
}

# Build local/yay first as it is the dependency to all the other images
docker-build yay $@

for build in mathematica root texlive; do
    docker-build $build $@
    docker save jp-ellis/${build}:build | \
        sudo docker-squash -verbose -t jp-ellis/${build}:latest | \
        docker load
done

wait
